Wip - few updates
Quentinchampenois/decidim pull request #6
Opened 2020-04-30 16:19 UTC by Quentinchampenois

#### :tophat: What? Why?

[Write description]

#### :pushpin: Related Issues
- Related to #?
- Fixes #?

#### :clipboard: Subtasks
- [x] Add `CHANGELOG` entry
- [ ] Add documentation regarding the feature 
- [ ] Add/modify seeds
- [ ] Add tests
- [ ] Another subtask

2020-05-04 16:03 UTC, armandfardeau requested changes
Thanks for your contribution, may you correct a few things before merging?

2020-05-04 16:03 UTC, armandfardeau commented on decidim-initiatives/app/forms/decidim/initiatives/admin/initiative_answer_form.rb
> +          when "published", "debatted", "examinated", "classified"
I may be better to Use the constant defined on Decidim::Initiatives class, then add published?

2020-05-04 16:03 UTC, armandfardeau commented on decidim-initiatives/spec/system/initiative_spec.rb
> +        expect(page).to have_content(I18n.l(base_initiative.answer_date, format: "%d/%m/%Y"))
Please use I18n format

2020-05-05 08:24 UTC, Quentinchampenois commented on decidim-initiatives/spec/system/initiative_spec.rb
> +        expect(page).to have_content(I18n.l(base_initiative.answer_date, format: "%d/%m/%Y"))
hi, thanks for the review. I agree with you and update it

2020-05-05 08:44 UTC, Quentinchampenois commented on decidim-initiatives/app/forms/decidim/initiatives/admin/initiative_answer_form.rb
> +          when "published", "debatted", "examinated", "classified"
Hi, thanks for your suggestion, I update it

2020-05-20 07:52 UTC, closed without merging